### ISSUE TITLE
lable not visible

### ISSUE THREAD

**Issue by AltamasBari** [payalmit/payalmit.github.io#1]
poor colour combination

**Comment by payalmit** [comment]
Bhai it was visible in laptop and i have set the color as white

**Comment by AltamasBari** [comment]
![Screenshot (149)](https://user-images.githubusercontent.com/44174307/81507273-c6fa9d80-9319-11ea-97bb-f05051b9d8c6.png)

**Comment by payalmit** [comment]
Ohk sorry bhai
Can i know what is the problem

**Comment by AltamasBari** [comment]
In .form lable
add color:white;
